"""Build-time asset pipeline for the 自嘲熊 desktop-pet plugin (optional tool).

The source artwork is an animated GIF (7 frames, 640x640, transparent). This
script extracts the frames, crops ONE union bounding box across all frames so
the character never jitters between frames, writes the web-ready WebP frames,
and emits the base64 module the client bundle inlines.

The plugin itself never runs Python: the generated files are committed, so this
script only matters if you want to re-derive the assets from your own artwork.

    python tools/build_assets.py          # requires Pillow

Layout:
    assets/source/zichaoxiong.gif   -> source artwork (input)
    assets/frames/frame-N.webp      -> trimmed display frames (committed)
    assets/frames-base64.js         -> generated, inlined by lib/client.js
    assets/sprite-sheet.webp        -> contact sheet for docs
"""

from __future__ import annotations

import base64
import io
import json
from pathlib import Path

from PIL import Image, ImageSequence

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "assets" / "source" / "zichaoxiong.gif"
FRAME_DIR = ROOT / "assets" / "frames"
DATA_MODULE = ROOT / "assets" / "frames-base64.js"

DISPLAY_SIZE = 320  # px; rendered at ~160 CSS px, so this is the 2x asset
PAD = 6
WEBP_QUALITY = 92


def encode_webp(frame: Image.Image) -> bytes:
    """Encode once; the same bytes feed both the file and the data URL."""
    buffer = io.BytesIO()
    frame.save(buffer, format="WEBP", quality=WEBP_QUALITY, method=6)
    data = buffer.getvalue()
    if not data:
        raise RuntimeError("WEBP encoder produced 0 bytes")
    return data


def union_bbox(frames: list[Image.Image]) -> tuple[int, int, int, int]:
    """One square crop shared by every frame (per-frame crops would jitter)."""
    boxes = [f.getchannel("A").getbbox() for f in frames]
    boxes = [b for b in boxes if b is not None]
    if not boxes:
        raise RuntimeError("every frame is fully transparent")
    left = min(b[0] for b in boxes)
    top = min(b[1] for b in boxes)
    right = max(b[2] for b in boxes)
    bottom = max(b[3] for b in boxes)
    cx, cy = (left + right) / 2, (top + bottom) / 2
    half = max(right - left, bottom - top) / 2 + PAD
    return (
        int(round(cx - half)),
        int(round(cy - half)),
        int(round(cx + half)),
        int(round(cy + half)),
    )


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit(f"missing source artwork: {SOURCE}")

    with Image.open(SOURCE) as image:
        frames = [frame.convert("RGBA") for frame in ImageSequence.Iterator(image)]
    if not frames:
        raise SystemExit("source artwork has no frames")

    cropped = [
        f.crop(union_bbox(frames)).resize((DISPLAY_SIZE, DISPLAY_SIZE), Image.LANCZOS)
        for f in frames
    ]

    FRAME_DIR.mkdir(parents=True, exist_ok=True)
    for stale in FRAME_DIR.glob("frame-*.webp"):
        stale.unlink()

    data_urls: list[str] = []
    for index, frame in enumerate(cropped):
        payload = encode_webp(frame)
        target = FRAME_DIR / f"frame-{index}.webp"
        target.write_bytes(payload)
        if target.stat().st_size != len(payload):
            raise RuntimeError(f"{target} size mismatch after write")
        data_urls.append("data:image/webp;base64," + base64.b64encode(payload).decode())
        print(f"  frame-{index}: {len(payload):>6} B")

    sheet = Image.new("RGBA", (DISPLAY_SIZE * len(cropped), DISPLAY_SIZE), (0, 0, 0, 0))
    for index, frame in enumerate(cropped):
        sheet.alpha_composite(frame, (index * DISPLAY_SIZE, 0))
    sheet.save(ROOT / "assets" / "sprite-sheet.webp", quality=WEBP_QUALITY, method=6)

    DATA_MODULE.write_text(
        "// Generated by tools/build_assets.py - do not edit by hand.\n"
        "// The idle frames, inlined by lib/client.js so the plugin needs no static route.\n"
        "export const FRAME_DATA_URLS = [\n"
        + "".join(f'  "{url}",\n' for url in data_urls)
        + "];\n",
        encoding="utf-8",
    )
    (ROOT / "assets" / "frames.json").write_text(
        json.dumps(
            {
                "displaySize": DISPLAY_SIZE,
                "frameCount": len(cropped),
                "webpQuality": WEBP_QUALITY,
                "source": "assets/source/zichaoxiong.gif",
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(cropped)} frames + {DATA_MODULE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
